services:
  backend:
    build: ./app/backend
    container_name: backend
    environment:
      - PORT_BACKEND=5000
      - AI_SERVICE_URL=${AI_SERVICE_URL}
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./app/frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge